# Generated by Django 4.0.5 on 2022-07-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, verbose_name='Client name')),
                ('client_org', models.CharField(max_length=255, unique=True, verbose_name='Client organization')),
                ('number', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('service', models.CharField(max_length=255)),
                ('fraud_score', models.FloatField(verbose_name='Fraud detector score')),
                ('service_class', models.PositiveSmallIntegerField()),
                ('service_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255, unique=True, verbose_name='Client name')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('address', models.CharField(max_length=255, unique=True, verbose_name='Address')),
            ],
        ),
    ]
