# Generated by Django 4.0.5 on 2022-07-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_bill_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='amount',
            field=models.CharField(max_length=10, verbose_name='Sum'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='number',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
    ]
